scanner:
    diff_only: True  # If False, the entire file touched by the Pull Request is scanned for errors. If True, only the diff is scanned.
    linter: pycodestyle  # Alternative option - flake8

pycodestyle:  # Valid if scanner.linter is pycodestyle
    max-line-length: 120
    ignore: []  # Errors and warnings to ignore
    exclude: []  # File path patterns to exclude

no_blank_comment: True  # If True, no comment is made on PR without any errors.

message:  # Customize the comment made by the bot
    opened:  # Messages when a new PR is submitted
        header: ""
        footer: ""
    updated:  # Messages when a PR is updated
        header: ""
        footer: ""
    no_errors: "There are no PEP 8 issues detected in this Pull Request. Good job!"
